mstep = out.tout(2) - out.tout(1);
ms = (1/100)/mstep;
json_struct = struct('time', out.tout(1:ceil(ms):length(out.tout)),...
                     'ox_pos', out.OxPositions,...
                     'ox_speed', out.OxSpeed,...
                     'pwm', out.pwmControl,...
                     'dutyCycle', out.dutyCycle,...
                     'task', out.task,...
                     'error_control', out.errorControl);
data = [json_struct];
save('forward_nerual_controll_N15_de{popsize:100, iter:200}.mat', 'data');